services:
  app:
    environment:
      - RAILS_ENV=test
      - MYSQL_HOST=db
    build:
      context: .
      dockerfile: ./Dockerfile
    image: "tkycraft/mahirun:rspec1.0"
    depends_on: {}
    volumes: []
    healthcheck: {}
    entrypoint: []

  mysql:
    volumes: []
    deploy:
      mode: replicated
      replicas: 0
